site_name: Lbb Notes
site_author: Lbb
repo_url: https://github.com/ban-l/lbb-notes
repo_name: lbb-notes
theme:
  name: material
plugins:
  - search
markdown_extensions:
  - admonition  # 支持提示框
  - codehilite  # 代码高亮
  - toc:  # 自动生成目录
      permalink: true
  - pymdownx.superfences  # 支持代码块嵌套
  - pymdownx.highlight  # 更好的代码高亮
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ban-l/lbb-notes